src/trendlines/routes.py
# -*- coding: utf-8 -*-

import json
from datetime import datetime
from datetime import timezone
from functools import partial

from marshmallow_peewee import ModelSchema
from flask import Blueprint as FlaskBlueprint
from flask import jsonify
from flask import render_template as _render_template
from flask import request
from flask.views import MethodView

from flask_rest_api import Api as _Api
from flask_rest_api import Blueprint
from werkzeug.routing import RoutingException

# peewee
from peewee import DoesNotExist
from peewee import IntegrityError
from playhouse.shortcuts import model_to_dict
from playhouse.shortcuts import update_model_from_dict

from trendlines import logger
from trendlines.__about__ import __version__
from . import db
from . import orm
from .error_responses import ErrorResponse
from . import utils

pages = FlaskBlueprint('pages', __name__)


# https://github.com/Nobatek/flask-rest-api/issues/51
class Api(_Api):
    def handle_http_exception(self, error):
        # Don't serialize redirects
        if isinstance(error, RoutingException):
            return error
        return super().handle_http_exception(error)


api_class = Api()
api = Blueprint("api", __name__,
                description="All API.")
api_datapoint = Blueprint("DataPoints", __name__,
                          description="CRUD datapoint(s)")
api_metric = Blueprint("Metrics", __name__,
                       description="CRUD metric(s)")


# Make sure all pages show our version.
render_template = partial(_render_template, version=__version__)


@api_class.definition("Metrics")
class MetricSchema(ModelSchema):
    class Meta:
        model = orm.Metric


@api_class.definition("DataPoints")
class DataPointSchema(ModelSchema):
    class Meta:
        model = orm.DataPoint


@pages.route("/", methods=['GET'])
@pages.route("/plot/<metric>", methods=["GET"])
def index(metric=None):
    """
    Main page.

    Also allows direct links to a specific plot.

    Parameters
    ----------
    metric : str or int, optional
        The metric_id or metric name to plot.
    """
    metric_name = None
    if metric is not None:
        # Support both metric_id and metric_name
        try:
            metric_id = int(metric)
            metric_name = orm.Metric.get(orm.Metric.metric_id == metric_id).name
        except ValueError:
            # We couldn't parse as an int, so it's a metric name instead.
            metric_name = metric

    metric_list = db.get_metrics()
    tree_data = utils.build_jstree_data(metric_list)

    return render_template('trendlines/index.html',
                           tree_data=tree_data,
                           metric_id=metric_name)


@api.route("/api/v1/data")
class Data(MethodView):
    def post(self):
        """
        Add a new value and possibly a metric if needed.

        Expected JSON payload has the following key/value pairs::

          metric: string
          value: numeric
          time: integer or missing
        """
        data = request.get_json()
        logger.debug("Received POST /api/v1/data: {}".format(data))

        try:
            metric = data['metric']
            value = data['value']
        except KeyError:
            logger.warning("Missing JSON keys 'metric' or 'value'.")
            return "Missing required key. Required keys are:", 400

        time = data.get('time', None)

        db.add_metric(metric)
        new = db.insert_datapoint(metric, value, time)

        msg = "Added DataPoint to Metric {}\n".format(new.metric)
        logger.info("Added value %s to metric '%s'" % (value, metric))
        return msg, 201


@api.route("/api/v1/data/<metric>")
class DataByName(MethodView):
    def get(self, metric):
        """
        Return data for a given metric as JSON.

        Parameters
        ----------
        metric : str or int
            The metric name or the metric internal id (int) to get data for.
        """
        logger.debug("GET /api/v1/data/%s" % metric)

        # Support both metric_id and metric_name
        try:
            metric_id = int(metric)
            metric_name = orm.Metric.get(orm.Metric.metric_id == metric_id).name
        except ValueError:
            # We couldn't parse as an int, so it's a metric name instead.
            metric_name = metric

        try:
            raw_data = db.get_data(metric_name)
            units = db.get_units(metric_name)
        except DoesNotExist:
            return ErrorResponse.metric_not_found(metric_name)

        if len(raw_data) == 0:
            return ErrorResponse.metric_has_no_data(metric_name)

        data = utils.format_data(raw_data, units)

        return jsonify(data)


@api_datapoint.route("/api/v1/datapoint")
class DataPoint(MethodView):
    @api_datapoint.response(DataPointSchema(many=True))
    def get(self):
        """
        Return all of the data for all metrics.
        """
        logger.debug("api: GET all datapoints")
        raw_data = db.get_datapoints()
        if len(raw_data) == 0:
            # do a thing.
            return ErrorResponse.no_data()

        data = [model_to_dict(m) for m in raw_data]

        # For now, fill in dummy values.
        return jsonify({"count": len(data),
                        "prev": None,
                        "next": None,
                        "results": data})

    @api_datapoint.response(DataPointSchema, code=201)
    def post(self):
        """
        Insert a new datapoint.

        Note that this is different from the "data" route, which will
        automatically create a new metric if needed. This route will not do so.
        """
        data = request.get_json()

        # Verify all required keys exist
        required = ['metric_id', 'value']
        try:
            metric_id = data['metric_id']
            value = data['value']
        except KeyError:
            return ErrorResponse.missing_required_key(required)

        timestamp = data.get('timestamp', None)

        try:
            metric = db.Metric.get(db.Metric.metric_id == metric_id)
        except db.Metric.DoesNotExist:
            return ErrorResponse.metric_not_found(metric_id)

        new = db.insert_datapoint(metric.name, value, timestamp)

        return jsonify(model_to_dict(new)), 201


@api_datapoint.route("/api/v1/datapoint/<datapoint_id>")
class DataPointById(MethodView):

    def _put_patch(self, datapoint_id, metric_id, value, timestamp):
        """
        PUT (replace) or PATCH (update) a datapoint.

        Handles the various DoesNotExist errors that can be raised.
        """
        try:
            db.update_datapoint(datapoint_id, metric_id, value, timestamp)
        except db.DataPoint.DoesNotExist:
            return ErrorResponse.datapoint_not_found(datapoint_id)
        except db.Metric.DoesNotExist:
            return ErrorResponse.metric_not_found(metric_id)

    @api_datapoint.response(DataPointSchema)
    def get(self, datapoint_id):
        """
        Return the data for a single datapoint.
        """
        logger.debug("api: GET datapoint by ID")
        try:
            raw_data = db.get_datapoint(datapoint_id)
        except DoesNotExist:
            return ErrorResponse.datapoint_not_found(datapoint_id)

        data = model_to_dict(raw_data)
        return jsonify(data)

    @api_datapoint.response(code=201)
    def put(self, datapoint_id):
        """
        Replace a datapoint with new values.
        """
        data = request.get_json()

        # Parse our json.
        try:
            metric_id = data['metric_id']
            value = data['value']
        except KeyError:
            return ErrorResponse.missing_required_key(['metric_id', 'value'])

        timestamp = data.get('timestamp', None)

        return self._put_patch(datapoint_id, metric_id, value, timestamp)


    @api_datapoint.response(code=204)
    def patch(self, datapoint_id):
        """
        Update parts of a datapoint with new values.
        """
        data = request.get_json()

        metric_id = data.get('metric_id', None)
        value = data.get('value', None)
        timestamp = data.get('timestamp', None)

        return self._put_patch(datapoint_id, metric_id, value, timestamp)

    @api_datapoint.response(code=204)
    def delete(self, datapoint_id):
        """
        Delete a datapoint.
        """
        logger.debug("'api: DELETE datapoint '%s'" % datapoint_id)

        try:
            found = db.DataPoint.get(db.DataPoint.datapoint_id == datapoint_id)
            found.delete_instance()
        except DoesNotExist:
            return ErrorResponse.datapoint_not_found(datapoint_id)
        else:
            return "", 204


@api_metric.route("/api/v1/metric")
class Metric(MethodView):
    @api_metric.response(MetricSchema(many=True))
    def get(self):
        """
        Return a list of all metrics in the database.
        """
        logger.debug("api: GET all metrics")
        raw_data = db.get_metrics()
        if len(raw_data) == 0:
            # do a thing.
            return ErrorResponse.no_data()

        data = [model_to_dict(m) for m in raw_data]

        # For now, fill in dummy values.
        return jsonify({"count": len(data),
                        "prev": None,
                        "next": None,
                        "results": data})

    @api_metric.response(MetricSchema, code=201)
    def post(self):
        """
        Create a new metric.

        Accepts JSON data with the following format:

        .. code-block::json
           {
             "name": "your.metric_name.here",
             "units": string, optional,
             "upper_limit": {float, optional},
             "lower_limit": {float, optional},
           }

        Returns ``201`` on success, ``400`` on malformed JSON data (such as when
        ``name`` is missing), or ``409`` if the metric already exists.

        See Also
        --------
        :func:`routes.get_metric_as_json`

src/trendlines/templates/trendlines/index.html
{% extends "trendlines/layout.html" %}

{% block body %}

<div id="content" class="container">
  <div class="row">
    <div class="col">
      <h1><a href="{{ url_for('pages.index') }}">Trendlines</a></h1>
      <h4>v{{ version }}</h4>
      <div id="apiLinks">
        <ul>
          <li><a target="_blank" href="{{ config.get('URL_PREFIX', '') }}/api/">API Reference (Swagger)</a></li>
          <li><a target="_blank" href="{{ config.get('URL_PREFIX', '') }}/api/redoc">API Reference (ReDoc)</a></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="row">
    <div id="tree" class="col-sm-3 order-1 border border-primary" style="height: 500px; overflow-y: scroll;">
      <!-- This div holds the left side: primarily the JS tree -->
      <div id="jstree-div">
      </div>

      <script>
        $(document).ready( function() {
          var treeData = {{ tree_data | tojson | safe }};

          // Populate the jsTree with the metric names.
          var metricId = {{ metric_id | tojson | safe }};
          populateTree(treeData, metricId, {{ config.get('URL_PREFIX', None) | tojson | safe }});
        });
      </script>
    </div>

    <div id="data" class="col-sm-9 order-2 border">
      <!-- The right side: the plot and buttons -->
      <div id="change-axis-buttons" class="btn-group btn-group-toggle" data-toggle="buttons">
        <label class="btn btn-primary active">
          <input id="x-axis-type-sequential" type="radio" name="x-axis-type" autocomplete="off" value="sequential" checked>Sequential
        </label>
        <label class="btn btn-primary">
          <input id="x-axis-type-time" type="radio" name="x-axis-type" autocomplete="off" value="time">Time Series
        </label>
      </div>

      <div id="graph" style="height: 500px;"></div>

    </div>
  </div>
</div>

{% endblock %}

<!-- vim: set expandtab tabstop=2 shiftwidth=2 softtabstop=2: -->

src/trendlines/templates/trendlines/layout.html
<!DOCTYPE html>
<head lang="en">

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- JavaScript -->
<script type="text/javascript" charset="utf-8" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script type="text/javascript" charset="utf-8" src="https://cdn.plot.ly/plotly-1.43.0.min.js"></script>
<script type="text/javascript" charset="utf-8" src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.7/jstree.min.js"></script>
<script type="text/javascript" charset="utf-8" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf-8" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf-8" src="{{ url_for('static', filename='core.js') }}"></script>

<!-- CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.7/themes/default/style.min.css" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />

<title>Trendlines</title>

</head>

<body>
  <header>
  </header>

  <main>
  {% block body %}
  {% endblock %}
  </main>

  <footer>
  </footer>

</body>
</html>

<!-- vim: set expandtab tabstop=2 shiftwidth=2 softtabstop=2: -->